actors:
  HonMarkHunt:
    image_url: /images/actors/alice.png
    name: HonMarkHunt
    url: http://sns.example.com/alice
  mnuma:
    image_url: /images/actors/alice.png
    name: mnuma
    url: http://sns.example.com/alice
  kyusuke:
    image_url: /images/actors/alice.png
    name: kyusuke
    url: http://sns.example.com/alice
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: alice
description: Shinjulu.LTの最近や周りにあったあれそれについてお話します
description_long: Shinjulu.LTの最近や周りにあったあれそれについてお話します
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: shinjukult
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: shinjuku-lt
url: http://example.com
